name = "GrowthParameterEstimation"
uuid = "f2d48b76-d258-4732-aa20-f5a609aab424"
version = "0.2.2"
authors = ["Kadin"]

[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BlackBoxOptim = "0.6"
CSV = "0.10"
DataFrames = "1"
DiffEqParamEstim = "2"
DifferentialEquations = "7"
Distributions = "0.25"
ForwardDiff = "0.10"
LsqFit = "0.13"
Optimization = "3, 5"
OptimizationBBO = "0.1"
OptimizationOptimJL = "0.1"
OrdinaryDiffEq = "6.70"
RecursiveArrayTools = "3"
StatsBase = "0.33"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "Random"]
