name = "GrowthParameterEstimationDocs"
version = "0.1.0"
authors = ["Kadin"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GrowthParameterEstimation = "f2d48b76-d258-4732-aa20-f5a609aab424"

[compat]
Documenter = "0.27, 1"
GrowthParameterEstimation = "0.1"
